name: Run test cases

on: [push, pull_request]

jobs:    
    run_test_cases:
        runs-on: ubuntu-latest
      
        container:
            image: erlang:22.1
            
        steps:
            - uses: actions/checkout@v1
            - name: run test cases
              run: |
                make xref
                make eunit
                make ct
                make cover
